# Disable Custom Header | ?disable_ch |...
#   http://10.16.0.29:8123/lovelace/default_view?disable_ch

# ToDo 2020-01-16
# Amcrest
# Presence Detection
# Scripts examples
# Notifications
# Temperature Presets

# 20220218 - Finally, back to working on HA OS so I am trying to get kiosk mode working...
#   https://github.com/maykar/kiosk-mode
# kiosk: -- Hides both the header and sidebar.
#     ?kiosk           to hide both header and sidebar
#     ?kiosk&cache     to make all views & dashboards both header and sidebar.
#        - This works for all query strings except for the utility strings listed below.
# Utility Query Strings
#   ?clear_km_cache   will clear all cached preferences
#   ?disable_km       will temporarily disable any modifications

kiosk_mode:
  admin_settings:
    kiosk: false
  non_admin_settings:
    kiosk: true
title: PkDr Admin
views:
  - title: PkDr Controls
    theme: M3-04-Magenta
    visible:
      - user: f2a7bc7c54114ae18850444b825ccc30
    path: pkdr-admin?disable_km
    require_admin: true
    cards:
      - type: light
        entity: light.rgbw_bulb_test
        name: RGBW Bulb Test
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        entity: switch.switch_test
        name: Switch Test
      - entities:
          - entity: switch.b1_lights
          - entity: switch.b2_lights
          - entity: switch.b3_lights
          - entity: switch.b4_lights
        show_header_toggle: true
        state_color: true
        title: Building Lights
        type: entities
      - entities:
          - entity: automation.building_lights_on
          - entity: automation.building_lights_off
          - entity: automation.b1_entrance_relock
          - entity: automation.building_lights_back_on
          - entity: automation.building_lights_back_off
          - entity: automation.apt01_climate_home
          - entity: automation.apt01_climate_away
          - entity: automation.apt01_entrance_relock
          - entity: automation.apt01_no_heat_with_ac
          - entity: automation.apt01_no_ac_with_heat
          - entity: automation.apt02_no_heat_with_ac
          - entity: automation.apt02_no_ac_with_heat
          - entity: automation.apt03_no_heat_with_ac
          - entity: automation.apt03_no_ac_with_heat
          - entity: automation.apt05_no_heat_with_ac
          - entity: automation.apt05_no_ac_with_heat
          - entity: automation.apt06_no_heat_with_ac
          - entity: automation.apt06_no_ac_with_heat
          - entity: automation.apt07_no_heat_with_ac
          - entity: automation.apt07_no_ac_with_heat
          - entity: automation.apt09_no_heat_with_ac
          - entity: automation.apt09_no_ac_with_heat
          - entity: automation.apt12_no_heat_with_ac
          - entity: automation.apt12_no_ac_with_heat
          - entity: automation.apt14_no_heat_with_ac
          - entity: automation.apt14_no_ac_with_heat
          # - entity: automation.outlet_on_every_2_1
          # - entity: automation.outlet_off_every_1_4
          # - entity: automation.apt14_climate_home
          # - entity: automation.apt14_climate_away
        show_header_toggle: true
        state_color: true
        title: PkDr Automations
        type: entities
      # 2-BDR
      - entities:
          - entity: light.apt01_bulb_entrance
          - entity: light.apt01_bulb_livingroom
          - entity: light.apt01_bulb_kitchen
          - entity: light.apt01_bulb_hall
          - entity: light.apt01_bulb_bedroom
          - entity: light.apt01_bulb_bedroom2
          - entity: light.apt01_light_bedroom
          - entity: switch.apt01_livingroom_iptv
          - entity: switch.apt01_ac
          - entity: switch.01_heat
          - entity: switch.apt01_vdb_door_lock
          - entity: switch.apt01_doorbell
          - entity: input_number.apt01_volume
          - entity: switch.apt01_bedroom_ender3
        show_header_toggle: true
        state_color: true
        title: Apt 1
        type: entities
      # 1-BDR
      - entities:
          - entity: light.apt02_bulb_entrance
          - entity: light.apt02_bulb_livingroom
          - entity: light.apt02_bulb_kitchen
          - entity: light.apt02_bulb_hall
          - entity: light.apt02_bulb_bedroom
          - entity: light.apt02_light_bedroom
          - entity: switch.apt02_livingroom_iptv
          - entity: switch.apt02_ac
          - entity: switch.02_heat
          - entity: switch.apt02_vdb_door_lock
          - entity: switch.apt02_doorbell
          - entity: input_number.apt02_volume
        show_header_toggle: true
        state_color: true
        title: Apt 2
        type: entities
      # 1-BDR
      - entities:
          - entity: light.apt03_bulb_entrance
          - entity: light.apt03_bulb_livingroom
          - entity: light.apt03_bulb_kitchen
          - entity: light.apt03_bulb_hall
          - entity: light.apt03_bulb_bedroom
          - entity: light.apt03_light_bedroom
          - entity: switch.apt03_livingroom_iptv
          - entity: switch.apt03_ac
          - entity: switch.03_heat
          - entity: switch.apt03_vdb_door_lock
          - entity: switch.apt03_doorbell
          - entity: input_number.apt03_volume
        show_header_toggle: true
        state_color: true
        title: Apt 3
        type: entities
      # 1-BDR
      - entities:
          - entity: light.apt05_bulb_entrance
          - entity: light.apt05_bulb_livingroom
          - entity: light.apt05_bulb_kitchen
          - entity: light.apt05_bulb_hall
          - entity: light.apt05_bulb_bedroom
          - entity: light.apt05_light_bedroom
          - entity: switch.apt05_livingroom_iptv
          - entity: switch.apt05_ac
          - entity: switch.05_heat
          - entity: switch.apt05_vdb_door_lock
          - entity: switch.apt05_doorbell
          - entity: input_number.apt05_volume
        show_header_toggle: true
        state_color: true
        title: Apt 5
        type: entities
      # 1-BDR
      - entities:
          - entity: light.apt06_bulb_entrance
          - entity: light.apt06_bulb_livingroom
          - entity: light.apt06_bulb_kitchen
          - entity: light.apt06_bulb_hall
          - entity: light.apt06_bulb_bedroom
          - entity: light.apt06_light_bedroom
          - entity: switch.apt06_livingroom_iptv
          - entity: switch.apt06_ac
          - entity: switch.06_heat
          - entity: switch.apt06_vdb_door_lock
          - entity: switch.apt05_doorbell
          - entity: input_number.apt05_volume
        show_header_toggle: true
        state_color: true
        title: Apt 6
        type: entities
      # 2-BDR
      - entities:
          - entity: light.apt07_bulb_entrance
          - entity: light.apt07_bulb_livingroom
          - entity: light.apt07_bulb_kitchen
          - entity: light.apt07_bulb_hall
          - entity: light.apt07_bulb_bedroom
          - entity: light.apt07_bulb_bedroom2
          - entity: light.apt07_light_bedroom
          - entity: light.apt07_light_bedroom2
          - entity: switch.apt07_livingroom_iptv
          - entity: switch.apt07_ac
          - entity: switch.07_heat
          - entity: switch.apt07_vdb_door_lock
          - entity: switch.apt07_doorbell
          - entity: input_number.apt07_volume
        show_header_toggle: true
        state_color: true
        title: Apt 7
        type: entities
      # 2-BDR
      - entities:
          - entity: light.apt08_bulb_entrance
          - entity: light.apt08_bulb_livingroom
          - entity: light.apt08_bulb_kitchen
          - entity: light.apt08_bulb_hall
          - entity: light.apt08_bulb_bedroom
          - entity: light.apt08_bulb_bedroom2
          - entity: light.apt08_light_bedroom
          - entity: light.apt08_light_bedroom2
          - entity: switch.apt08_livingroom_iptv
          - entity: switch.apt08_ac
          - entity: switch.08_heat
          - entity: switch.apt08_vdb_door_lock
          - entity: switch.apt08_doorbell
          - entity: input_number.apt08_volume
        show_header_toggle: true
        state_color: true
        title: Apt 8
        type: entities
      # 1-BDR
      - entities:
          - entity: light.apt09_bulb_entrance
          - entity: light.apt09_bulb_livingroom
          - entity: light.apt09_bulb_kitchen
          - entity: light.apt09_bulb_hall
          - entity: light.apt09_bulb_bedroom
          - entity: switch.apt09_livingroom_iptv
          - entity: switch.apt09_ac
          - entity: switch.09_heat
          - entity: switch.apt09_vdb_door_lock
          - entity: switch.apt09_doorbell
          - entity: input_number.apt09_volume
        show_header_toggle: true
        state_color: true
        title: Apt 9
        type: entities
      # 2-BDR
      - entities:
          - entity: light.apt11_bulb_entrance
          - entity: light.apt11_bulb_livingroom
          - entity: light.apt11_bulb_kitchen
          - entity: light.apt11_bulb_hall
          - entity: light.apt11_bulb_bedroom
          - entity: light.apt11_bulb_bedroom2
          - entity: light.apt11_light_bedroom
          - entity: light.apt11_light_bedroom2
          - entity: switch.apt11_livingroom_iptv
          - entity: switch.apt11_ac
          - entity: switch.11_heat
          - entity: switch.apt11_vdb_door_lock
          - entity: switch.apt11_doorbell
          - entity: input_number.apt11_volume
        show_header_toggle: true
        state_color: true
        title: Apt 11
        type: entities
      # 2-BDR
      - entities:
          - entity: light.apt12_bulb_entrance
          - entity: light.apt12_bulb_livingroom
          - entity: light.apt12_bulb_kitchen
          - entity: light.apt12_bulb_hall
          - entity: light.apt12_bulb_bedroom
          - entity: light.apt12_bulb_bedroom2
          - entity: light.apt12_light_bedroom
          - entity: light.apt12_light_bedroom2
          - entity: switch.apt12_livingroom_iptv
          - entity: switch.apt12_ac
          - entity: switch.12_heat
          - entity: switch.apt12_vdb_door_lock
          - entity: switch.apt12_doorbell
          - entity: input_number.apt12_volume
        show_header_toggle: true
        state_color: true
        title: Apt 12
        type: entities
      # 1-BDR
      - entities:
          - entity: light.apt13_bulb_entrance
          - entity: light.apt13_bulb_livingroom
          - entity: light.apt13_bulb_kitchen
          - entity: light.apt13_bulb_hall
          - entity: light.apt13_bulb_bedroom
          - entity: switch.apt13_livingroom_iptv
          - entity: switch.apt13_ac
          - entity: switch.13_heat
          - entity: switch.apt13_vdb_door_lock
          - entity: switch.apt13_doorbell
          - entity: input_number.apt13_volume
        show_header_toggle: true
        state_color: true
        title: Apt 13
        type: entities
      # 1-BDR
      - entities:
          - entity: light.apt14_bulb_entrance
          - entity: light.apt14_bulb_livingroom
          - entity: light.apt14_bulb_kitchen
          - entity: light.apt14_bulb_hall
          - entity: light.apt14_bulb_bedroom
          - entity: light.apt14_light_bedroom
          - entity: switch.apt14_livingroom_iptv
          - entity: switch.apt14_ac
          - entity: switch.apt14_heat
          - entity: switch.apt14_vdb_door_lock
          - entity: switch.apt14_doorbell
          - entity: input_number.apt14_volume
        show_header_toggle: true
        state_color: true
        title: Apt 14
        type: entities
      # 2-BDR
      - entities:
          - entity: light.apt12_bulb_entrance
          - entity: light.apt12_bulb_livingroom
          - entity: light.apt12_bulb_kitchen
          - entity: light.apt12_bulb_hall
          - entity: light.apt12_bulb_bedroom
          - entity: light.apt12_bulb_bedroom2
          - entity: light.apt12_light_bedroom
          - entity: light.apt12_light_bedroom2
          - entity: switch.apt12_livingroom_iptv
          - entity: switch.apt12_ac
          - entity: switch.12_heat
          - entity: switch.apt12_vdb_door_lock
          - entity: switch.apt12_doorbell
          - entity: input_number.apt12_volume
        show_header_toggle: true
        state_color: true
        title: Apt 12
        type: entities
      # Test - Kodi Notifications
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        entity: script.kodi_notification
        name: Apt01 Notify
        icon_height: 150px
      # Apartment-Wide Temperature Readings
      - type: entities
        entities:
        # Buildings
          - entity: sensor.b1_temperature
            name: B1
            icon: mdi:temperature-fahrenheit
          - entity: sensor.b2_temperature
            name: B2
            icon: mdi:temperature-fahrenheit
          - entity: sensor.b3_temperature
            name: B3
            icon: mdi:temperature-fahrenheit
          - entity: sensor.b4_temperature
            name: B4
            icon: mdi:temperature-fahrenheit
        # Apartments
          - entity: sensor.apt01_temperature
            name: '01'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt02_temperature
            name: '02'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt03_temperature
            name: '03'
            icon: mdi:temperature-fahrenheit
          # - entity: sensor.apt04_temperature
          #   name: '04'
          #   icon: mdi:temperature-fahrenheit
          - entity: sensor.apt05_temperature
            name: '05'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt06_temperature
            name: '06'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt07_temperature
            name: '07'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt08_temperature
            name: '08'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt09_temperature
            name: '09'
            icon: mdi:temperature-fahrenheit
          # - entity: sensor.apt10_temperature
          #   name: '10'
          #   icon: mdi:temperature-fahrenheit
          - entity: sensor.apt11_temperature
            name: '11'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt12_temperature
            name: '12'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt13_temperature
            name: '13'
            icon: mdi:temperature-fahrenheit
          - entity: sensor.apt14_temperature
            name: '14'
            icon: mdi:temperature-fahrenheit
          # - entity: sensor.apt15_temperature
          #   name: '15'
          #   icon: mdi:temperature-fahrenheit
          - entity: sensor.apt16_temperature
            name: '16'
            icon: mdi:temperature-fahrenheit
        show_header_toggle: false
        state_color: false
        title: PkDr Temperatures

      - type: entities
        entities:
          - switch.01_heat
          - switch.02_heat
          - switch.03_heat
          - switch.04_heat
          - switch.b1_end_switch_override
          - switch.05_heat
          - switch.06_heat
          - switch.07_heat
          - switch.08_heat
          - switch.b2_end_switch_override
          - switch.09_heat
          - switch.10_heat
          - switch.11_heat
          - switch.12_heat
          - switch.b3_end_switch_override
          - switch.13_heat
          - switch.14_heat
          - switch.15_heat
          - switch.16_heat
          - switch.b4_end_switch_override
        title: PkDr Heat
        show_header_toggle: true
        state_color: true
      - type: entities
        entities:
          - switch.apt01_vdb_door_lock
          - switch.02_lock
          - switch.apt03_vdb_door_lock
          - switch.04_lock
          - switch.05_lock
          - switch.apt06_vdb_door_lock
          - switch.07_lock
          - switch.apt08_vdb_door_lock
          - switch.09_lock
          - switch.10_lock
          - switch.apt11_vdb_door_lock
          - switch.12_lock
          - switch.apt13_vdb_door_lock
          - switch.apt14_vdb_door_lock
          - switch.15_lock
          - switch.apt16_vdb_door_lock
        show_header_toggle: true
        state_color: true
        title: PkDr Locks
      - type: entities
        entities:
          - switch.b1_kiosks_odd
          - switch.b1_kiosks_even
          - switch.b2_kiosks_odd
          - switch.b2_kiosks_even
          - switch.b3_kiosks_odd
          - switch.b3_kiosks_even
          - switch.b4_kiosks_odd
          - switch.b4_kiosks_even
        show_header_toggle: true
        state_color: true
        title: PkDr Kiosks
      - type: entities
        entities:
          - switch.b2_kiosks
          - switch.b3_kiosks
          - switch.b4_kiosks
        show_header_toggle: true
        state_color: true
        title: PkDr Kiosks (Old Way)
      - type: entities
        entities:
          - switch.b1_doorbells_odd
          - switch.b1_doorbells_even
          - switch.b2_doorbells_odd
          - switch.b2_doorbells_even
          - switch.b3_doorbells_odd
          - switch.b3_doorbells_even
          - switch.b4_doorbells_odd
          - switch.b4_doorbells_even
        show_header_toggle: true
        state_color: true
        title: PkDr Video Doorbells
      - type: entities
        entities:
          - switch.b1_entrance_vdb
          - switch.b2_entrance_vdb
          - switch.b3_entrance_vdb
          - switch.b4_entrance_vdb
          - switch.b1_vdb_door_lock
          - switch.b1_entrance_buttons
          - switch.b1_entrance_video
          - switch.b2_entrance_lock
          - switch.b2_entrance_buttons
          - switch.b2_entrance_video
          - switch.b3_entrance_lock
          - switch.b3_entrance_buttons
          - switch.b3_entrance_video
          - switch.b4_entrance_lock
          - switch.b4_entrance_buttons
          - switch.b4_entrance_video
        show_header_toggle: true
        state_color: true
        title: PkDr Entrance
